{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
    release: monitoring
spec:
  endpoints:
    - port: http
      path: /metrics/
      interval: 15s
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
{{- end }}